import { useState, useEffect } from 'react'
import { X } from 'lucide-react'
import { mockEmployeeService, mockAdminService } from '@/services/mock-data'
import { cn } from '@/utils'
import type { Department, EmployeeCredentials } from '@/types'

interface Props {
  onClose: () => void
  onCreated: (creds: EmployeeCredentials) => void
}

export function CreateEmployeeModal({ onClose, onCreated }: Props) {
  const [departments, setDepartments] = useState<Department[]>([])
  const [loading, setLoading] = useState(false)
  const [form, setForm] = useState({
    first_name: '', last_name: '', email: '', phone: '', dob: '',
    gender: '' as 'male' | 'female' | 'other' | '',
    department_id: '', designation: '', joining_date: '',
    employment_type: 'full_time' as string, work_location: '', role: 'employee' as string,
  })

  useEffect(() => { mockAdminService.getDepartments().then(setDepartments) }, [])

  const updateField = (field: string, value: string) => setForm(prev => ({ ...prev, [field]: value }))

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    try {
      const creds = await mockEmployeeService.create(form)
      onCreated(creds)
    } finally {
      setLoading(false)
    }
  }

  const inputCls = 'w-full px-3 py-2.5 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-700 text-sm text-slate-900 dark:text-white placeholder:text-slate-400'
  const labelCls = 'block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5'

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="fixed inset-0 bg-black/50 animate-fade-in" onClick={onClose} />
      <div className="relative w-full max-w-2xl bg-white dark:bg-slate-800 rounded-2xl shadow-2xl animate-scale-in max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-slate-700 sticky top-0 bg-white dark:bg-slate-800 z-10">
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white">Add New Employee</h2>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-700 text-slate-400">
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-5">
          <p className="text-sm text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20 p-3 rounded-lg">
            Employee ID and Login ID will be auto-generated by the system. A temporary password will be created.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className={labelCls}>First Name <span className="text-rose-500">*</span></label>
              <input type="text" value={form.first_name} onChange={(e) => updateField('first_name', e.target.value)} placeholder="Enter first name" className={inputCls} required />
            </div>
            <div>
              <label className={labelCls}>Last Name <span className="text-rose-500">*</span></label>
              <input type="text" value={form.last_name} onChange={(e) => updateField('last_name', e.target.value)} placeholder="Enter last name" className={inputCls} required />
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className={labelCls}>Email <span className="text-rose-500">*</span></label>
              <input type="email" value={form.email} onChange={(e) => updateField('email', e.target.value)} placeholder="Enter email" className={inputCls} required />
            </div>
            <div>
              <label className={labelCls}>Phone</label>
              <input type="tel" value={form.phone} onChange={(e) => updateField('phone', e.target.value)} placeholder="Enter phone" className={inputCls} />
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className={labelCls}>Date of Birth</label>
              <input type="date" value={form.dob} onChange={(e) => updateField('dob', e.target.value)} className={inputCls} />
            </div>
            <div>
              <label className={labelCls}>Gender</label>
              <select value={form.gender} onChange={(e) => updateField('gender', e.target.value)} className={inputCls}>
                <option value="">Select gender</option>
                <option value="male">Male</option>
                <option value="female">Female</option>
                <option value="other">Other</option>
              </select>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className={labelCls}>Department <span className="text-rose-500">*</span></label>
              <select value={form.department_id} onChange={(e) => updateField('department_id', e.target.value)} className={inputCls} required>
                <option value="">Select department</option>
                {departments.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}
              </select>
            </div>
            <div>
              <label className={labelCls}>Designation <span className="text-rose-500">*</span></label>
              <input type="text" value={form.designation} onChange={(e) => updateField('designation', e.target.value)} placeholder="Enter job title" className={inputCls} required />
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className={labelCls}>Joining Date <span className="text-rose-500">*</span></label>
              <input type="date" value={form.joining_date} onChange={(e) => updateField('joining_date', e.target.value)} className={inputCls} required />
            </div>
            <div>
              <label className={labelCls}>Employment Type</label>
              <select value={form.employment_type} onChange={(e) => updateField('employment_type', e.target.value)} className={inputCls}>
                <option value="full_time">Full Time</option>
                <option value="part_time">Part Time</option>
                <option value="contract">Contract</option>
                <option value="internship">Internship</option>
              </select>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className={labelCls}>Work Location</label>
              <input type="text" value={form.work_location} onChange={(e) => updateField('work_location', e.target.value)} placeholder="e.g. Bangalore, India" className={inputCls} />
            </div>
            <div>
              <label className={labelCls}>Role <span className="text-rose-500">*</span></label>
              <select value={form.role} onChange={(e) => updateField('role', e.target.value)} className={inputCls} required>
                <option value="employee">Employee</option>
                <option value="hr">HR Officer</option>
                <option value="admin">Administrator</option>
              </select>
            </div>
          </div>

          <div className="flex items-center gap-3 pt-2">
            <button type="submit" disabled={loading} className={cn('px-6 py-2.5 rounded-lg text-sm font-semibold text-white', loading ? 'bg-primary/60 cursor-not-allowed' : 'bg-primary hover:bg-primary-dark')}>
              {loading ? 'Creating...' : 'Create Employee'}
            </button>
            <button type="button" onClick={onClose} className="px-5 py-2.5 rounded-lg text-sm font-medium text-slate-600 dark:text-slate-400 border border-slate-300 dark:border-slate-600 hover:bg-slate-50 dark:hover:bg-slate-800">
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
